name: copy_updated_epg_files

on:
  workflow_run:
    workflows: ["tempest_epg_grabber"], ["merge_epg_files"] 
    types:
      - completed   
  workflow_dispatch:
  
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare destination repository
      run: |
        git clone https://x-access-token:${{ secrets.copy_files }}@github.com/s0ndip/s0ndip.github.io.git
        mkdir -p s0ndip.github.io/epg
    
    - name: Copy selected files
      run: |
        cp tempest_config/epg/jiotv.xml.gz s0ndip.github.io/epg
        cp tempest_config/epg/tataplay.xml.gz s0ndip.github.io/epg
        cp epg.xml.gz s0ndip.github.io/epg
        
    - name: Commit and push changes
      run: |
        cd s0ndip.github.io
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add epg
        git commit -m "Automated epg"
        git push
